services:
    kozma.net:
        build: .
        environment:
            - dbToken=$dbToken
            - database=$database
            - botToken=$botToken
            - energyMarket=$energyMarket
        image: kozma
        restart: unless-stopped