services:
    kozma.net:
        build: .
        environment:
            - dbToken=$dbToken
            - database=$database
            - botToken=$botToken
            - energyMarket=$energyMarket
            - cogmaster=$cogmaster
        image: kozma
        restart: unless-stopped
        networks:
            - cogmaster-net

networks:
  cogmaster-net:
    external: true